package leaven

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// TestAssimilate places testdata/projects (if needed), emits LLVM IR, and
// runs leaven. Skips when workspaced/clang 22/cargo are missing.
// Under -short, skips the slow rhai cargo emit.
func TestAssimilate(t *testing.T) {
	t.Run("csmith", testAssimilateCsmith)
	t.Run("rhai", testAssimilateRhai)
}

func testAssimilateCsmith(t *testing.T) {
	root := requireProject(t, "csmith", "src/RandomProgramGenerator.cpp")
	srcDir := filepath.Join(root, "src")
	build := t.TempDir()
	writeCsmithConfig(t, build)

	clangxx, isystem := clangXX22(t)
	srcs, err := filepath.Glob(filepath.Join(srcDir, "*.cpp"))
	if err != nil {
		t.Fatal(err)
	}
	// Generated by cmake; stub so the TU that references git_version links in IR.
	gitV := filepath.Join(build, "git_version.cpp")
	if err := os.WriteFile(gitV, []byte("const char git_version[] = \"leaven\";\n"), 0644); err != nil {
		t.Fatal(err)
	}
	srcs = append(srcs, gitV)

	var emitted, clangFail int
	for _, src := range srcs {
		base := strings.TrimSuffix(filepath.Base(src), ".cpp")
		ll := filepath.Join(build, base+".ll")
		args := []string{"-S", "-emit-llvm", "-std=c++17", "-O0",
			"-fno-exceptions", "-fno-rtti", "-fno-discard-value-names",
			"-DHAVE_CONFIG_H",
			"-I", build, "-I", srcDir}
		args = append(args, isystem...)
		args = append(args, "-o", ll, src)
		cmd := exec.Command(clangxx, args...)
		out, err := cmd.CombinedOutput()
		if err != nil {
			clangFail++
			t.Logf("clang++ skip %s: %s", filepath.Base(src), lastErrorLine(out))
			continue
		}
		emitted++
		assimilateLL(t, ll)
	}
	if emitted == 0 {
		t.Fatalf("clang++ emitted 0/%d TUs (%d skipped)", len(srcs), clangFail)
	}
	t.Logf("leaven ok on %d TUs (%d clang++ skipped)", emitted, clangFail)
}

func testAssimilateRhai(t *testing.T) {
	if testing.Short() {
		t.Skip("-short: skip rhai cargo emit")
	}
	root := requireProject(t, "rhai", "Cargo.toml")
	clang, sysroot, libdir := clang22LinkEnv(t)
	cmd := exec.Command("mise", "exec", "--", "cargo", "rustc", "--bin", "rhai-run", "--release",
		"--", "-C", "panic=abort", "--emit=llvm-ir", "-C", "debuginfo=0")
	cmd.Dir = root
	cmd.Env = append(os.Environ(),
		"CC="+clang,
		"CXX="+filepath.Join(filepath.Dir(clang), "clang++"),
		"CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER="+clang,
		"RUSTFLAGS=-C debuginfo=0 -C linker="+clang+" -C link-arg=--sysroot="+sysroot+" -C link-arg=-L"+libdir,
	)
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("cargo rustc rhai-run: %v\n%s", err, tailBytes(out, 4000))
	}
	matches, err := filepath.Glob(filepath.Join(root, "target", "release", "deps", "rhai_run-*.ll"))
	if err != nil || len(matches) == 0 {
		t.Fatalf("no rhai_run-*.ll after cargo rustc (err=%v)\n%s", err, tailBytes(out, 2000))
	}
	assimilateLL(t, matches[0])
}

func assimilateLL(t *testing.T, ll string) {
	t.Helper()
	m, err := parseIRFile(ll)
	if err != nil {
		t.Fatalf("parse %s: %v", filepath.Base(ll), err)
	}
	var buf bytes.Buffer
	if err := Compile(&buf, m, "main"); err != nil {
		t.Fatalf("compile %s: %v", filepath.Base(ll), err)
	}
	if _, err := format.Source(buf.Bytes()); err != nil {
		t.Fatalf("gofmt %s: %v", filepath.Base(ll), err)
	}
}

func requireProject(t *testing.T, name, marker string) string {
	t.Helper()
	root := filepath.Join("testdata", "projects", name)
	mark := filepath.Join(root, marker)
	if _, err := os.Stat(mark); err != nil {
		syncProjects(t)
	}
	if _, err := os.Stat(mark); err != nil {
		t.Skipf("%s not placed after workspaced apply: %v", root, err)
	}
	abs, err := filepath.Abs(root)
	if err != nil {
		t.Fatal(err)
	}
	return abs
}

func syncProjects(t *testing.T) {
	t.Helper()
	if _, err := exec.LookPath("mise"); err != nil {
		t.Skip("mise not on PATH")
	}
	cmd := exec.Command("mise", "exec", "--", "workspaced", "codebase", "apply")
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Skipf("workspaced codebase apply: %v\n%s", err, tailBytes(out, 2000))
	}
}

func writeCsmithConfig(t *testing.T, dir string) {
	t.Helper()
	const hdr = `#define HAVE_DLFCN_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_LRAND48 1
#define HAVE_MEMORY_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define PACKAGE "csmith"
#define PACKAGE_NAME "csmith"
#define PACKAGE_STRING "csmith 2.3.0"
#define PACKAGE_VERSION "2.3.0"
#define VERSION "2.3.0"
`
	if err := os.WriteFile(filepath.Join(dir, "config.h"), []byte(hdr), 0644); err != nil {
		t.Fatal(err)
	}
}

func clangXX22(t *testing.T) (bin string, isystem []string) {
	t.Helper()
	out, err := exec.Command("mise", "exec", "conda:clangxx@22.1.8", "--", "sh", "-c", "command -v clang++").CombinedOutput()
	if err != nil {
		t.Skipf("mise clang++ 22: %v\n%s", err, out)
	}
	bin = strings.TrimSpace(string(out))
	prefix := filepath.Dir(filepath.Dir(bin))
	matches, _ := filepath.Glob(filepath.Join(prefix, "lib", "gcc", "*", "*", "include", "c++"))
	if len(matches) == 0 {
		return bin, nil
	}
	inc := matches[0]
	flags := []string{"-isystem", inc}
	if ts, _ := filepath.Glob(filepath.Join(inc, "*-*")); len(ts) > 0 {
		flags = append(flags, "-isystem", ts[0])
	}
	return bin, flags
}

func clang22LinkEnv(t *testing.T) (clang, sysroot, libdir string) {
	t.Helper()
	out, err := exec.Command("mise", "exec", "conda:clangxx@22.1.8", "--", "sh", "-c", "command -v clang").CombinedOutput()
	if err != nil {
		t.Skipf("mise clang 22: %v\n%s", err, out)
	}
	clang = strings.TrimSpace(string(out))
	prefix := filepath.Dir(filepath.Dir(clang))
	sysroot = filepath.Join(prefix, "x86_64-conda-linux-gnu", "sysroot")
	libdir = filepath.Join(prefix, "lib")
	return clang, sysroot, libdir
}

func lastErrorLine(b []byte) string {
	s := strings.TrimSpace(string(b))
	if s == "" {
		return ""
	}
	lines := strings.Split(s, "\n")
	for i := len(lines) - 1; i >= 0; i-- {
		line := strings.TrimSpace(lines[i])
		if line != "" {
			return line
		}
	}
	return s
}

func tailBytes(b []byte, n int) string {
	if len(b) <= n {
		return string(b)
	}
	return fmt.Sprintf("…(%d bytes omitted)\n%s", len(b)-n, b[len(b)-n:])
}
